### ISSUE TITLE
Request for lnception-V3 finetuned checkpoint for image generation metrics and CLIP R@1,5 used checkpoint

### ISSUE THREAD

**Issue by DragonLiu1995** [kaist-ami/Sound2Scene#2]
Hi,

Thanks for releasing the code for this amazing work! After I carefully read through the paper and supplementary materials, I have 2 questions. 

1. I found that you fine-tuned inception-V3 on VggSound data in order to calculate the FID and IS score. Could you please release the fine-tuned checkpoint so that I could use it to compare?

2. Which specific checkpoint did you use for CLIP to calculate those CLIP R@1, 5 metrics?

Thanks in advance for guidance and clarifications!

**Comment by sbkim052** [comment]
I updated the README for more information.
Please check them:)
