### ISSUE TITLE
Regarding the training dataset for Sound2Scene.

### ISSUE THREAD

**Issue by AndreJJXu** [kaist-ami/Sound2Scene#3]
How was the training dataset for the Sound2Scene model acquired? Thanks!

**Comment by ardasnck** [comment]
Hi! 

Please check the README with detailed explanation about how we acquired the audio-visual dataset.

https://github.com/postech-ami/Sound2Scene#highly-correlated-audio-visual-pair-dataset

**Comment by AndreJJXu** [comment]
Thanks!

**Comment by AndreJJXu** [comment]
Dear author, how can I download the dataset VEGAS? I cannot find the dataset :(
