### ISSUE TITLE
Regarding the dataset

### ISSUE THREAD

**Issue by AndreJJXu** [kaist-ami/Sound2Scene#4]
Dear author, how can I download the dataset VEGAS? I cannot find the dataset :(

**Comment by sbkim052** [comment]
Hi, please let me know your email address

**Comment by AndreJJXu** [comment]
52285901001@stu.ecnu.edu.cn, thanks~

**Comment by DthdZK** [comment]
Dear author, could you please send me this dataset VEGAS? My email address is kaizheng2000@163.com. Thanks a lot! @sbkim052
